# Generated by Django 2.2.5 on 2021-09-03 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redessociales',
            name='github',
        ),
    ]
